import type * as Types from '~/_codegen/types.ts';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type AppFruitAvatarFragment = { __typename?: 'FruitAvatar', url: string };

export type AppSubFruitFragment = { __typename?: 'Fruit', id: string, slug: string, name?: string | null, avatar?: { __typename?: 'FruitAvatar', url: string } | null };

export type AppFruitFragment = { __typename?: 'Fruit', id: string, slug: string, description?: string | null, short_description?: string | null, name?: string | null, images?: Array<string | null> | null, opening_year?: number | null, type: string, color?: string | null, avatar?: { __typename?: 'FruitAvatar', url: string } | null, children: Array<{ __typename?: 'Fruit', id: string, slug: string, name?: string | null, avatar?: { __typename?: 'FruitAvatar', url: string } | null }>, parentage: Array<{ __typename?: 'Fruit', id: string, slug: string, name?: string | null, avatar?: { __typename?: 'FruitAvatar', url: string } | null }> };

export type AppFruitQueryVariables = Types.Exact<{
  slug: Types.Scalars['String']['input'];
}>;


export type AppFruitQuery = { __typename?: 'Query', fruit?: { __typename?: 'Fruit', id: string, slug: string, description?: string | null, short_description?: string | null, name?: string | null, images?: Array<string | null> | null, opening_year?: number | null, type: string, color?: string | null, avatar?: { __typename?: 'FruitAvatar', url: string } | null, children: Array<{ __typename?: 'Fruit', id: string, slug: string, name?: string | null, avatar?: { __typename?: 'FruitAvatar', url: string } | null }>, parentage: Array<{ __typename?: 'Fruit', id: string, slug: string, name?: string | null, avatar?: { __typename?: 'FruitAvatar', url: string } | null }> } | null };

export const AppFruitAvatarFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"AppFruitAvatar"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"FruitAvatar"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}}]}}]} as unknown as DocumentNode<AppFruitAvatarFragment, unknown>;
export const AppSubFruitFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"AppSubFruit"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Fruit"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"slug"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"avatar"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"AppFruitAvatar"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"AppFruitAvatar"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"FruitAvatar"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}}]}}]} as unknown as DocumentNode<AppSubFruitFragment, unknown>;
export const AppFruitFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"AppFruit"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Fruit"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"slug"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"short_description"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"avatar"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"AppFruitAvatar"}}]}},{"kind":"Field","name":{"kind":"Name","value":"children"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"AppSubFruit"}}]}},{"kind":"Field","name":{"kind":"Name","value":"parentage"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"AppSubFruit"}}]}},{"kind":"Field","name":{"kind":"Name","value":"images"}},{"kind":"Field","name":{"kind":"Name","value":"opening_year"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"color"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"AppFruitAvatar"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"FruitAvatar"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"AppSubFruit"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Fruit"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"slug"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"avatar"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"AppFruitAvatar"}}]}}]}}]} as unknown as DocumentNode<AppFruitFragment, unknown>;
export const AppFruitDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"AppFruit"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"slug"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"fruit"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"slug"},"value":{"kind":"Variable","name":{"kind":"Name","value":"slug"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"AppFruit"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"AppFruitAvatar"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"FruitAvatar"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"AppSubFruit"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Fruit"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"slug"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"avatar"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"AppFruitAvatar"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"AppFruit"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Fruit"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"slug"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"short_description"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"avatar"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"AppFruitAvatar"}}]}},{"kind":"Field","name":{"kind":"Name","value":"children"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"AppSubFruit"}}]}},{"kind":"Field","name":{"kind":"Name","value":"parentage"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"AppSubFruit"}}]}},{"kind":"Field","name":{"kind":"Name","value":"images"}},{"kind":"Field","name":{"kind":"Name","value":"opening_year"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"color"}}]}}]} as unknown as DocumentNode<AppFruitQuery, AppFruitQueryVariables>;