fragment AppFruitAvatar on FruitAvatar {
  url
}

fragment AppSubFruit on Fruit {
  id
  slug
  name
  avatar {
    ...AppFruitAvatar
  }
}

fragment AppFruit on Fruit {
  id
  slug
  description
  short_description
  name
  avatar {
    ...AppFruitAvatar
  }
  children {
    ...AppSubFruit
  }
  parentage {
    ...AppSubFruit
  }
  images
  opening_year
  type
  color
}

query AppFruit($slug: String!) {
  fruit(slug: $slug) {
    ...AppFruit
  }
}
