fragment SubItemNetworkFruit on Fruit {
  id
  name
  slug
  opening_year
  color
  avatar {
    ...AppFruitAvatar
  }
}

fragment NetworkFruit on Fruit {
  id
  name
  slug
  color
  parentage {
    ...SubItemNetworkFruit
  }
  children {
    ...SubItemNetworkFruit
  }
  avatar {
    ...AppFruitAvatar
  }
}

query FruitsNetwork($type: String, $slugs: [String!], $take: Int) {
  fruits(type: $type, take: $take, slugs: $slugs) {
    totalCount
    data {
      ...NetworkFruit
    }
  }
}