fragment SubItemListOfFruits on Fruit {
  id
  slug
}

fragment FruitsListItem on Fruit {
  id
  slug
  name
  opening_year
  images
  short_description
  avatar {
    ...AppFruitAvatar
  }
  children {
    ...SubItemListOfFruits
  }
  parentage {
    ...SubItemListOfFruits
  }
}

query ListOfFruits($type: String, $skip: Int, $take: Int, $search: String) {
  fruits(type: $type, skip: $skip, take: $take, search: $search) {
    totalCount
    pageInfo {
      skip
      take
      hasNextPage
    }
    data {
      ...FruitsListItem
    }
  }
}