fragment SubItemListOfFruits on Fruit {
  id
  slug
}

query ListOfFruits($type: String!, $skip: Int, $take: Int) {
  fruits(type: $type, skip: $skip, take: $take) {
    totalCount
    pageInfo {
      skip
      take
      hasNextPage
    }
    data {
      id
      slug
      name
      opening_year
      images
      short_description
      avatar {
        ...AppFruitAvatar
      }
      children {
        ...SubItemListOfFruits
      }
      parentage {
        ...SubItemListOfFruits
      }
    }
  }
}